### PR TITLE
Add code quality badge from Codacy

### PR DESCRIPTION
**Pull request by yinonavraham**
This PR does not relate to any issue.

Changes proposed in this pull request:
* Add code quality badge from Codacy.
  The goal is to increase the trust on the library by making its quality visible

Request feedback from: @mcumings

### CODE REVIEW

**Comment by yinonavraham** [comment]
The markdown files are analyzed by the [RemarkLint](https://app.codacy.com/p/171945/patterns/list?engine=f1eec388-0526-4c6c-954e-9b20b51bd9e7) engine.
According to a Codacy article about the [Codacy Configuration File](https://support.codacy.com/hc/en-us/articles/115002130625-Codacy-Configuration-File): 
> "If you want to disable an engine, that needs to be done directly in the [Code Patterns](https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns) page."

Therefor I disabled this code pattern engine in Codacy for the project. Also, since the engine is now disabled I think it is OK to not exclude the markdown files. But if you want to exclude them (or any other files) it can be done using the Codacy config file. 

Currently the only code pattern engines which are enabled are PMD and Codestyle. Both can be configured using their own config file (see [Code Patterns](https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns)). I did not want to enforce any specific styling on a project which is not my own.

Cheers!

**Comment by mcumings** [comment]
I do not appear to be able to configure the project.  I must not have administrative rights over it on Codacy's site.  By creating the configuration for this project I'm assuming it automatically granted you these rights?

**Comment by yinonavraham** [comment]
I'm in the admins team of the eBay organization in Codacy, this is why I have rights...
I just created a new team in Codacy for this project and added you with write privileges. I think that should do the trick. Please update me if not.

**Comment by mcumings** [comment]
That did it, thanks!

**Pull request merged**
